language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

branches:
  only:
    - master
    - develop
    - experimental

-before_install:
  - sudo apt-get -qq -y update

install:
  - sudo apt-get install -y python-software-properties
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install -y git qgis python-qgis xvfb python-nose python-coverage pyflakes python-nosexcover python-scientific python-beautifulsoup
  - pip install --upgrade pip
  - pip install --upgrade pep8
  - pip install --upgrade pylint
  - echo "Checking out test data at" `date`
  - make testdata

before_script:
  - echo "Build starting on " `date`
  - export QGIS_PREFIX_PATH=/usr
  - export PYTHONPATH=${QGIS_PREFIX_PATH}/share/qgis/python/:${QGIS_PREFIX_PATH}/share/qgis/python/plugins:`pwd`
  - echo "PYTHONPATH:" $PYTHONPATH
  - export LD_LIBRARY_PATH=${QGIS_PREFIX_PATH}/lib

script:
  - make pep8
  - make pylint
  - xvfb-run --server-args="-screen 0, 1024x768x24" nosetests -A 'not slow' -v --with-id --with-xcoverage --with-xunit --verbose --cover-package=safe safe

notifications:
  irc:
    channels:
      - "irc.freenode.org#inasafe"
    use_notice: true

  email:
    - tim@kartoza.com
